// This file holds all the data for the mega menu.
// It's structured to make it easy to create the nested lists.

export const menuData = {
    Fashion: {
        "Men's Top Wear": ["All", "Men's T-Shirts", "Men's Casual Shirts", "Men's Formal Shirts", "Men's Kurtas", "Men's Ethnic Sets", "Men's Blazers", "Men's Raincoat", "Men's Windcheaters", "Men's Suit"],
        "Men's Bottom Wear": [],
        "Women Ethnic": [],
        "Men Footwear": [],
        "Women Footwear": [],
        "Watches and Accessories": [],
        "Women Western": [],
        "Bags, Suitcases & Luggage": [],
        "Kids": [],
        "Essentials": [],
        "Winter": [],
    },
    Electronics: {
        "Audio": ["All", "Bluetooth Headphones", "Wired Headphones", "True Wireless Earbuds", "Bluetooth Speakers", "Soundbars", "Home Theatres", "TV Streaming Device", "Remote Control", "DTH Set top box"],
        "Electronics GST Store": [],
        "Cameras & Accessories": [],
        "Computer Peripherals": [],
        "Gaming": [],
        "Health & Personal Care": [],
        "Laptop Accessories": [],
        "Laptop and Desktop": [],
        "MobileAccessory": [],
        "Powerbank": [],
        "Smart Home automation": [],
    },
    "Home & Furniture": {
        "Home Furnishings": ["All", "Bed Linens", "Bedsheets", "Blankets", "Curtains & Accessories", "Bath linen", "Floor coverings", "Covers & protectors", "Cushions & Pillows", "Kitchen Linen Sets", "Table Linen Sets", "Sofa & curtain fabrics", "Branded Collections"],
        "Furniture": [],
        "Living Room Furniture": [],
        "Kitchen & Dining": [],
        "Bedroom Furniture": [],
        "Space Saving Furniture": [],
        "Home Decor": [],
        "Tools & Utility": [],
        "Work Space Furniture": [],
        "Kids Furniture": [],
        "Lightings & Electricals": [],
        "Cleaning & Bath": [],
        "Pet & Gardening": [],
    },
    "Beauty, Food..": {
        "Beauty & Personal Care": ["View All", "Bath & Oral Care", "Personal Hygiene", "Eye Makeup", "Face Makeup", "Lip Makeup", "Hair Care", "Bath Essentials", "Women's Personal Hygiene", "Body & Skin Care"],
        "Men's Grooming": [],
        "Food & Drinks": [],
        "Nutrition & Health Care": [],
        "Baby Care": [],
        "Toys & School Supplies": [],
        "Sports & Fitness": [],
        "Books": [],
        "Music": [],
        "Stationery & Office Supplies": [],
        "Auto Accessories": [],
    },
    // You can add more categories here like "TVs & Appliances", etc.
};
